---
name: "Create a git tag"
on: 
    workflow_dispatch: 
permissions:
    contents: write
jobs:
    tag:
        name: "Add a git tag according to pyproject.toml"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                clean: true
                submodules: true
                ref: ${{ github.head_ref }}
                fetch-depth: 0
            - name: Setup PDM
              uses: pdm-project/setup-pdm@v4
            - name: Install dependencies
              run: | 
                pdm install --plugins
            - name: Setup git configuration
              run: |
                git config --global user.name 'Github actions (carstencodes)'
                git config --global user.email 'carstencodes@users.noreply.github.com'
            - name: Create a new tag
              run: pdm bump tag
            - name: Push changes
              run: git push origin HEAD --tags
